### ISSUE TITLE
Set units

### ISSUE THREAD

**Issue by pshotton** [pimoroni/weatherhat-python#13]
It should be possible to set the unit for each measurement, for instance wind speed in m/s, km/h, mph or knots

**Comment by ageeandakeyboard** [comment]
Hi,

The windspeed outputs in the SI units of meters per second which is reasonably easy to convert.

```
wind_speed_kph = wind_speed_mps * 3.6
wind_speed_mph = wind_speed_mps * 2.23694
```

I have been using the build in google units convertor for these values :)
https://www.google.com/search?q=convert+m%2Fs+to+mph

This should give you all the multipliers you need.

Regards
Gee
