### ISSUE TITLE
Overview page on weather.py doesn't display correctly

### ISSUE THREAD

**Issue by orbrey** [pimoroni/weatherhat-python#14]
weather.py example only displays half the screen. This is using a fresh install on RPi OS Buster. Tested installing by both pip3 and manual clone of repo then running install.sh.

![image](https://user-images.githubusercontent.com/6640794/183124127-8b3f00f2-8974-417a-a5a8-bab4aac80557.png)

Other pages on the same example display fine, it's just the overview page that looks off.

**Comment by helgibbons** [comment]
Just set up a Weather HAT  with a fresh 32-bit Bullseye image (with desktop) and a Pi Zero W and it's working OK for me, following the instructions in https://learn.pimoroni.com/article/getting-started-with-weather-hat . If anyone else is running into this issue it might be worth checking you have all the dependencies for the examples?

`sudo pip3 install fonts font-manrope pyyaml adafruit-io numpy`

Running the example with `python3` instead of just `python` might also be worth a try?

**Comment by remidone** [comment]
![IMG-20230128-WA0005](https://user-images.githubusercontent.com/123834271/215285789-d172f3d7-0aff-49ba-81d9-23686b5dc1e1.jpeg)

**Comment by helgibbons** [comment]
Have you got I2C and SPI enabled in `sudo raspi-config`?

**Comment by remidone** [comment]
yes
![immagine](https://user-images.githubusercontent.com/123834271/215467790-6c66c256-1817-4b92-96da-56db1710228b.png)

**Comment by helgibbons** [comment]
Interesting - it seems to be having trouble seeing the sensors? It's probably worth checking that the HAT is securely pushed down onto the GPIO pins and making a good connection?

You could also try running:
`i2cdetect -y 1`

to see if the I2C devices are being detected?

**Comment by remidone** [comment]
In sudo raspi-config I tried three times but it always asked me to confirm to enable Ic2 and spi. Now I'll try i2cdetect -y 1

**Comment by remidone** [comment]
![immagine](https://user-images.githubusercontent.com/123834271/215477185-3eb2116d-229d-4522-b857-661605410a19.png)

**Comment by remidone** [comment]
Lcd.py works correctly

**Comment by helgibbons** [comment]
Sounds like there may be something wrong with the hardware if your sensors aren't showing up - if you drop an email to support@pimoroni.com with a link to this issue and your order number they should be able to sort you out with a replacement.

**Comment by helgibbons** [comment]
Closing this one for now - if anyone's still having issues with the display rendering incorrectly with the new release please let us know :)
