### ISSUE TITLE
Temperature running too hot

### ISSUE THREAD

**Issue by Kingsy** [pimoroni/weatherhat-python#21]
Hi, 

So I have my weather hat attached to a raspberry pi 4, its a plastic case outside.
I actually have another weather station running along side it, that station says the current temp is 

13.05 degrees.
My phone says its 11 degrees

However the raspberry pi weather hat says its

Temperature: 21.91 *C

Needless to say it is not 22 degrees outside, I can only think the pi is running too hot as the device temp is
System temp: 29.41 *C

Have you had this issue before? 
Does further offsets need to be applied?
What raspberry pi is recommended for the hat?

Is there anything I can do about this? i.e can you extend the temperature probe on a wire do it is not attached to the board?

Thanks

**Comment by Kingsy** [comment]
I think its also worth mentioning that the first reading of basic.py is correct (or at least it seems so)
But subsequent readings are far far too high.

System temp: 21.31 *C
Temperature: 13.81 *C
Temperature: -7.50 *C

Humidity:    76.65 %
Dew point:   16.64 *C

Light:       0.00 Lux

Pressure:    698.45 hPa

Wind (avg):  0.00 m/sec

Rain:        0.00 mm/sec

Wind (avg):  45.00 degrees (North East)



System temp: 28.67 *C
Temperature: 21.17 *C
Temperature: -7.50 *C

Humidity:    24.35 %
Dew point:   13.54 *C

Light:       0.89 Lux

Pressure:    968.94 hPa

Wind (avg):  0.00 m/sec

Rain:        0.00 mm/sec

Wind (avg):  270.00 degrees (West)

**Comment by IanD42** [comment]
The weatherhat onboard is subjected to heat from the pi typical, on my Pi Zero installation this was 7-10 degrees high
to compensate for this adjust the sensor.temperature_offset
![image](https://user-images.githubusercontent.com/33552425/211827385-d67f89a9-f0b2-41a2-8255-4102510a092f.png)
Hope this helps
Ian

**Comment by IanD42** [comment]
"I think its also worth mentioning that the first reading of basic.py is correct (or at least it seems so)
But subsequent readings are far far too high."
Sorry the first readings from the BME280 sensor are incorrect and should be discarded.
To avoid the high temperature readings, see previous comment.
Also I've added a separate external BME280 connected to the weatherhat and this avoids having to apply a temperature offset
Ian

**Comment by Kingsy** [comment]
Ahhh this is very very useful thanks.
Couple more questions here.

In terms of connecting the extra probe, is this simply done via the I2C connector on the back of the hat as the page suggests?
"Want to add on more I2C sensors? No problem, there's an solderless I2C header located on the back of the HAT that you can poke jumper / DuPont wires (or even a [Breakout Garden slot](https://shop.pimoroni.com/products/breakout-extender)) in to."

if that is the case, the code you are using to read the sensor.

`# BME280 External Sensor
from bme280 import BME280
from smbus import SMBus
bus = SMBus(1)
bme280 = BME280(i2c_dev=bus, i2c_addr=0x77)
`

Is the SMBus, and i2c_addr always the same? i.e would I be able to use this exact code for reading the temps from my new external sensor?

Thanks

**Comment by IanD42** [comment]
Yes, the External BME is connected directly to the i2c header on the weatherhat

To confirm i2c addresses:
The connected I2C address can be detected using i2c-tools. 
First of all, install the i2c-tools by running the following command in the Raspberry Pi Terminal:
sudo apt-get install -y i2c-tools

Now run the following command to scan connected I2C adresses:
sudo i2cdetect -y 1
Output:
![Screenshot 2023-01-12 04.44.55.png](https://user-images.githubusercontent.com/33552425/211982481-3ce893fd-1c4c-418b-954a-97389f420b50.png)

**Comment by Kingsy** [comment]
Thanks so much for the info.
And what about SMBus ?

**Comment by IanD42** [comment]
> Thanks so much for the info.
> And what about SMBus ?

Check out the following Youtube video from "Expalinig Computers"
https://www.youtube.com/watch?v=ChQpD2gsC20&t=8s

this gives a good explaination( and code) in connecting a BME280 directly to a Pi

I just adapted this to include with the test.py code for use with a weather hat and external BME280
Ian

**Comment by Kingsy** [comment]
Thanks for the information.
