### ISSUE TITLE
"Unexpected token S in JSON at position 195"

### ISSUE THREAD

**Issue by IanD42** [pimoroni/weatherhat-python#22]
Pi Zero W + Pimoroni WeatherHat
==========================
When atempting to publish weather data to my mqtt broker I receive (in a Node-Red flow) the following error msg;

![Screenshot 2023-01-15 14.57.21.png](https://user-images.githubusercontent.com/33552425/212548699-d51adcfa-d5e4-4747-bb59-befb301dcf2a.png)
Extract of code to send pyload to mqtt broker:
![Screenshot 2023-01-15 14.49.57.png](https://user-images.githubusercontent.com/33552425/212548260-abcd666e-7352-4e3a-ab4f-693130a07b6a.png)

When printing the same data, all values:  temperature, pressue, humidity.... are printed as expected

Removing the following line from the mqqt payload, all the remaining sensor valuse are now publish without error

![Screenshot 2023-01-15 14.39.12.png](https://user-images.githubusercontent.com/33552425/212547279-d0712759-9664-4179-ad7d-945f2a24da93.png)

I asume  there is a formating problem with the output  of:
"wind_Cardinal": {wind_direction_cardinal}, \

I have very limitted experiance with python/json code and would appreciate any guidance how to fix this.

**Comment by helgibbons** [comment]
Is `wind_direction_cardinal` definitely a valid value?

You could add a `print(wind_direction_cardinal)` to your code to check (or see if it throws a useful error)?

**Comment by IanD42** [comment]
Extract of code to print wind direction Degrees and Cardinal (North, North
East, East, South East, South......)
[image: image.png]
Gives the following output:

[image: f34c7375-0ad5-4794-bb37-e95170358be3.png]
Have run this previously with Wind Cardinal output spread over all 8
(45Degree offsets) cardinal positions
This would suggest text output from Wind Cardinal is causing the issue when
publishing to my mqtt broker.

The payload received by my mqtt broker (all sensors
excluding "Wind_Cardinal"[image: image.png]
It's only when the text output  of "Wind Cardinal" is sent the error occurs
and halts delivery of the payload

Is there any alternative python formatting of the "Wind_Cardial" output
that would be accepted by the mqtt broker?

**Comment by IanD42** [comment]
> Is `wind_direction_cardinal` definitely a valid value?
YES
> You could add a `print(wind_direction_cardinal)` to your code to check (or see if it throws a useful error)?
It Prints the Wind Cardinals, Nort,North East, East...

                                             SOLVED

json.dumps() function will convert a subset of Python objects into a json string
added thr following to my python code

import json
replaced:
wind_direction_cardinal = (wind_direction.average_compass())
with:
wind_direction_cardinal = json.dumps(wind_direction.average_compass())

Now the full weather sensors are published to mqtt broker:


![Screenshot 2023-01-16 20.12.18.png](https://user-images.githubusercontent.com/33552425/212758804-d5869750-9d90-4d94-951d-f89990640d5d.png)

**Comment by helgibbons** [comment]
Excellent, glad you figured it out! Closing for now - feel free to reopen if necessary.
