### ISSUE TITLE
Timeout waiting for ADC conversion

### ISSUE THREAD

**Issue by sebastian-raubach** [pimoroni/weatherhat-python#25]
I've got the weather hat working reasonably well with this library even though I had some issues with the rain measurements seeming off.

However, since I set it to run permanently yesterday, it crashed last night with the following traceback:

```
Traceback (most recent call last):
  File "/home/pi/weatherhat-python/examples/rpi-weather.py", line 109, in <module>
    sensor.update(interval=interval)
  File "/usr/local/lib/python3.9/dist-packages/weatherhat/__init__.py", line 160, in update
    self.wind_direction_raw = self._ioe.input(PIN_WV)
  File "/usr/local/lib/python3.9/dist-packages/ioexpander/__init__.py", line 704, in input
    raise RuntimeError("Timeout waiting for ADC conversion!")
RuntimeError: Timeout waiting for ADC conversion!
```

`interval` where I call `sensor.update` is set to `5.0` like  in most of the examples.

Anyone got any idea why this might be happening? I've wrapped the whole thing in a `try` `except` for now under the assumption that this is a blip and next time I try to get measurements, it'll work again, but I can't be sure yet.

**Comment by helgibbons** [comment]
Sorry for the lack of reply here! Hopefully you've got things working in the meantime, but if you're still having problems with the latest version of the software please let us know.
