### ISSUE TITLE
installation script does not perform some updates

### ISSUE THREAD

**Issue by Solarbytes** [pimoroni/weatherhat-python#27]
Hi there,
Pi4B
Raspbian Bullseye full OS with desktop

I just installed the weather hat and wanted to report the following issues with the installation script:
1. the process advises to run the installation script as root but as I did that, I got the message that the script should not be run as root
2. the instructions say that the script will activate I2C and SPI but for me, it didn't, which caused errors when running weather.py
3. the module for the TFT screen was not installed as part of the installation script.

After fixing those issues, the weather.py script ran fine, however, there are large differences between what the Pimoroni Hat (PH) reports and what my Oregon Scientific (OS) station reports:

Temperature inside the house: 31.8 according to PH, 26.6 according to OS (OS seems to be more accurate as the external temperature is now 23C)
Relative humidity: 41% according to PH, 57% according to OS (OS seems to be more accurate)

Next, I ran the script BME280.py and here is what it reports:
Device temperature: 39.41 *C
Humidity:           24.14 %

this is very confusing because "device temperature" is not the same as "ambient temperature", so what is the hat actually reporting on? does weather.py report on ambient temperature and BME280.py reports on the device's temperature?

Finally, why is the humidity reported by this second script so far off the one reported by weather.py?

What could explain those differences?

Thanks,
Gaetano.

**Comment by Solarbytes** [comment]
Just to clarify, I followed instructions on the website: https://learn.pimoroni.com/article/getting-started-with-weather-hat

I have meanwhile found the offset parameter for temperature, that makes sense. I can see that on github that I2c and SPI needed enabling manually, however, the web site say the script does that. I read through the script and found a section that executes a "sed s/" command seemingly to remove the # in front of some lines but I was unable to determine which lines are affected as there is no reference to i2c or spi ,it almost looks like every line that is commented out is turned into an active line but I could be misunderstanding that code, my unix skills are rudimentary and rusty...

**Comment by helgibbons** [comment]
We've just updated the installer - hopefully it should now enable I2C and SPI correctly :)
