### ISSUE TITLE
How do you turn off the screen?

### ISSUE THREAD

**Issue by skillmatic-co** [pimoroni/weatherhat-python#9]
I will be running my Pi on a 12v battery system, so I'm looking to conserve power where ever I can. I wont be using the LCD screen at all. I see by default it's powered on (however nothing displayed).

Is there a way to power off the LCD screen?

**Comment by Gadgetoid** [comment]
IIRC the backlight is pulled high by default, so to turn it off you'll need to set-up the backlight pin and pull it low:

```
import RPi.GPIO as GPIO
GPIO.setup(13, GPIO.OUT)
GPIO.output(13, GPIO.LOW)
```

**Comment by Jennnifers** [comment]
I made a small python script and added it to my crontab to run at every boot:

```
import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(12, GPIO.OUT)
GPIO.output(12, GPIO.LOW)
```

**Comment by ageeandakeyboard** [comment]
Thanks for your help @Jennnifers 
I'll close the issue now 
Regards
Gee
